### ISSUE TITLE
Kinesis agent file deletion access

### ISSUE THREAD

**Issue by Mahalakshmi-Shanmugam** [awslabs/kinesis-agent-windows#17]
Hi,
The agent perfectly reads data from the input files; but is there a way to configure the agent to delete the input files once the data is processed and sent to the destination?

Thanks in advance.

**Comment by dhhoang** [comment]
@Mahalakshmi-Shanmugam  The Kinesis agent doesn't do that, the reason is that we need to collect data from log files that are constantly being appended, and the agent has no way to know whether a log file will or will not have more data in the future.
Usually the logging software (like NLog or log4net ) does offer archiving configurations that automatically clean up old log files.
I'd recommend looking into those.   
Does that answer your question?

**Comment by dhhoang** [comment]
Closing this issue due to no further requests
